# Generated by Django 3.0.6 on 2020-06-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('processed', models.BooleanField(default='False')),
                ('progress_time', models.IntegerField(default=0)),
                ('total_frame', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
