# Generated by Django 3.0.6 on 2020-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='id',
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
